# Pre-commit configuration for GitPersona
# This runs all validations locally before committing
repos:
  # Go formatting with local gofmt
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt
        language: system
        args: [-s, -w]
        types: [go]

  # Go import formatting with local goimports
  - repo: local
    hooks:
      - id: goimports
        name: goimports
        entry: goimports
        language: system
        args: [-w]
        types: [go]

  # Go linting with golangci-lint (less strict)
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint
        language: system
        args: [run, --disable=errcheck, --disable=unused, --disable=staticcheck, --timeout=5m]
        pass_filenames: false
        types: [go]

  # Go security vulnerability scanning
  - repo: local
    hooks:
      - id: govulncheck
        name: govulncheck
        entry: govulncheck
        language: system
        args: [./...]
        pass_filenames: false
        types: [go]

  # Go vet analysis
  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: go
        language: system
        args: [vet, ./...]
        pass_filenames: false
        types: [go]

  # Go test runner
  - repo: local
    hooks:
      - id: go-test
        name: go test
        entry: go
        language: system
        args: [test, -v, -timeout=5m, ./...]
        pass_filenames: false
        types: [go]

  # Go build verification
  - repo: local
    hooks:
      - id: go-build
        name: go build
        entry: go
        language: system
        args: [build, -o, /tmp/gitpersona-test, .]
        pass_filenames: false
        types: [go]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: debug-statements
