# Pre-commit configuration for gitshift
# This runs basic validations locally before committing
repos:
  # Go formatting with local gofmt
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt
        language: system
        args: [-s, -w]
        types: [go]

  # Go vet analysis
  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: go
        language: system
        args: [vet, ./...]
        pass_filenames: false
        types: [go]

  # Go build verification
  - repo: local
    hooks:
      - id: go-build
        name: go build
        entry: go
        language: system
        args: [build, -o, /tmp/gitshift-test, .]
        pass_filenames: false
        types: [go]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
