version: '3.8'

services:
  # Main application service
  gitpersona:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitpersona
    volumes:
      # Mount host config and SSH directories
      - ~/.config/gitpersona:/home/appuser/.config/gitpersona
      - ~/.ssh:/home/appuser/.ssh:ro
      # Mount current directory for development
      - .:/workspace
    working_dir: /workspace
    environment:
      - HOME=/home/appuser
    stdin_open: true
    tty: true
    command: ["/bin/bash"]

  # Development environment with Go tools
  dev:
    image: golang:1.25-alpine
    container_name: gitpersona-dev
    volumes:
      - .:/workspace
      - ~/.config/gitpersona:/root/.config/gitpersona
      - ~/.ssh:/root/.ssh:ro
      - go-mod-cache:/go/pkg/mod
    working_dir: /workspace
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    stdin_open: true
    tty: true
    command: ["/bin/sh"]
    depends_on:
      - gitpersona

  # Testing environment
  test:
    image: golang:1.25-alpine
    container_name: gitpersona-test
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg/mod
    working_dir: /workspace
    environment:
      - CGO_ENABLED=0
    command: |
      sh -c "
        apk add --no-cache git &&
        go mod download &&
        go test -v -cover ./...
      "
    depends_on:
      - gitpersona

  # Git server for testing (optional)
  git-server:
    image: gitea/gitea:1.21-alpine
    container_name: gitpersona-git
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
    restart: unless-stopped
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    profiles:
      - git-testing

volumes:
  go-mod-cache:
    driver: local
  gitea-data:
    driver: local

networks:
  default:
    name: gitpersona-network
